version: '3'
services: 
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Jinpachi.01"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  sales-data-api:
    build: .
    ports:
      - "8080:80"
    depends_on: 
      - ms-sql-server
